/* dlg_config.h.  Generated automatically by configure.  */
/*
 * The configure script expands this as a set of definitions
 */

#define DIALOG_PATCHDATE 20260107
#define DIALOG_VERSION "1.3"
#define GCC_NORETURN __attribute__((noreturn))
#define GCC_PRINTF 1
#define GCC_PRINTFLIKE(fmt,var) __attribute__((format(printf,fmt,var)))
#define GCC_SCANF 1
#define GCC_SCANFLIKE(fmt,var) __attribute__((format(scanf,fmt,var)))
#define GCC_UNUSED __attribute__((unused))
#define HAVE_BTOWC 1
#define HAVE_COLOR 1
#define HAVE_DIRENT_H 1
#define HAVE_DLG_FORMBOX 1
#define HAVE_DLG_GAUGE 1
#define HAVE_DLG_MIXEDFORM 1
#define HAVE_DLG_TAILBOX 1
#define HAVE_DLG_TRACE 1
#define HAVE_FLUSHINP 1
#define HAVE_FSEEKO 1
#define HAVE_GETATTRS 1
#define HAVE_GETBEGX 1
#define HAVE_GETBEGY 1
#define HAVE_GETBEGYX 1
#define HAVE_GETCURX 1
#define HAVE_GETCURY 1
#define HAVE_GETMAXX 1
#define HAVE_GETMAXY 1
#define HAVE_GETMAXYX 1
#define HAVE_GETPARX 1
#define HAVE_GETPARY 1
#define HAVE_GETPARYX 1
#define HAVE_ICONV 1
#define HAVE_INTTYPES_H 1
#define HAVE_LANGINFO_CODESET 1
#define HAVE_MATH_FUNCS 1
#define HAVE_MBLEN 1
#define HAVE_MBRLEN 1
#define HAVE_MBRTOWC 1
#define HAVE_MBSTATE_T 1
#define HAVE_MBTOWC 1
#define HAVE_MEMORY_H 1
#define HAVE_MIXEDGAUGE 1
#define HAVE_MKTIME 1
#define HAVE_NCURSES_H 1
#define HAVE_NL_LANGINFO_1STDAY 1
#define HAVE_RC_FILE 1
#define HAVE_RC_FILE2 1
#define HAVE_SEARCH_H 1
#define HAVE_SETLOCALE 1
#define HAVE_SGTTY_H 1
#define HAVE_SIZECHANGE 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRCASECMP 1
#define HAVE_STRFTIME 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_TERMIO_H 1
#define HAVE_TERM_H 1
#define HAVE_TSEARCH 1
#define HAVE_TYPE_CHTYPE 1
#define HAVE_UNCTRL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_USE_DEFAULT_COLORS 1
#define HAVE_WAITPID 1
#define HAVE_WCHGAT 1
#define HAVE_WCSRTOMBS 1
#define HAVE_WCSTOMBS 1
#define HAVE_WCTOB 1
#define HAVE_WCTOMB 1
#define HAVE_WCURSYNCUP 1
#define HAVE_WGETPARENT 1
#define HAVE_WHIPTAIL 1
#define HAVE_WSYNCUP 1
#define HAVE_XDIALOG 1
#define HAVE_XDIALOG2 1
#define ICONV_CONST /* nothing */
#define MIXEDCASE_FILENAMES 1
#define NCURSES 1
#define NEED_WCHAR_H 1
#define PACKAGE "dialog"
#define RETSIGTYPE void
#define STDC_HEADERS 1
#define SYSTEM_NAME "linux-gnu"
#define TIME_WITH_SYS_TIME 1
#define TYPE_CHTYPE_IS_SCALAR 1
